import Head from 'next/head'
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.grid}>
          <a
            href="/agent_bookkeeping"
            className={styles.card}
          >
            <h2>老Z会计工作室</h2>
          </a>

          <a
            href="/software_development"
            className={styles.card}
          >
            <h2>老G软件工作室</h2>
          </a>


          <p>
          「Powered by  
          <a
            href="https://webify.cloudbase.net/"
          > CloudBase Webify</a>」
          </p>
          
        </div>
      </main>
    </div>
  )
}
